'use client';

import React, { useState, useEffect, Suspense } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import AppShell from '@/components/ui/AppShell';
import { getRecoveryPlan } from '@/services/recoveryService';
import { RecoveryPlan } from '@/types';
import { Zap, Sparkles, Calendar, Clock, ArrowRight, BookOpen, CheckCircle2, Sliders } from 'lucide-react';

function RecoveryContent() {
  const searchParams = useSearchParams();
  const courseId = searchParams.get('courseId') || 'course-os-a';

  const [plan, setPlan] = useState<RecoveryPlan | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function loadPlan() {
      const data = await getRecoveryPlan(courseId);
      setPlan(data);
      setIsLoading(false);
    }
    loadPlan();
  }, [courseId]);

  if (isLoading || !plan) {
    return (
      <div style={{ padding: '40px', textAlign: 'center', color: '#94a3b8' }}>
        Formulating AI Recovery Plan...
      </div>
    );
  }

  return (
    <>
      {/* Header */}
      <div style={{ marginBottom: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
          <span className="badge" style={{ background: '#FFFFFF', color: 'var(--ink)', border: '1px solid var(--line)' }}>
            <Sparkles size={12} color="var(--brass)" /> AI Academic Recovery Planner
          </span>
        </div>
        <h1 style={{
          fontFamily: 'var(--font-serif)',
          fontSize: '1.8rem',
          fontWeight: 800,
          color: 'var(--ink)',
          marginBottom: '4px',
          letterSpacing: '-0.02em'
        }}>
          Syllabus Recovery Plan & Recommendations
        </h1>
        <p style={{ color: 'var(--ink-muted)', fontSize: '0.88rem' }}>
          Optimized extra-lecture schedule generated by AI to eliminate syllabus deficit before term end.
        </p>
      </div>

      {/* Target Course Summary Glass Card */}
      <div className="glass-card" style={{
        padding: '24px',
        marginBottom: '24px',
        background: '#FFFFFF',
        border: '1px solid var(--line)'
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px', flexWrap: 'wrap', gap: '12px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
              <h2 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.4rem', fontWeight: 800, color: 'var(--ink)' }}>
                {plan.courseName}
              </h2>
              <span className="badge" style={{ background: 'var(--paper)', color: 'var(--ink)', border: '1px solid var(--line)' }}>
                {plan.section}
              </span>
              <span style={{ fontSize: '0.85rem', color: 'var(--ink-muted)' }}>
                ({plan.courseCode})
              </span>
            </div>
            <div style={{ fontSize: '0.85rem', color: 'var(--ink-muted)' }}>
              Assigned Faculty: <strong style={{ color: 'var(--ink)' }}>{plan.facultyName}</strong>
            </div>
          </div>

          <Link href="/hod/recovery/what-if" style={{ textDecoration: 'none' }}>
            <button className="btn-secondary" style={{ padding: '8px 16px', fontSize: '0.82rem', gap: '6px' }}>
              <Sliders size={14} color="var(--ink)" /> Open What-If Simulator
            </button>
          </Link>
        </div>

        {/* 5 Metric Badges Row */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(auto-fit, minmax(130px, 1fr))',
          gap: '12px',
          background: 'var(--paper)',
          padding: '16px',
          borderRadius: '6px',
          border: '1px solid var(--line)'
        }}>
          <div>
            <div style={{ fontSize: '0.72rem', color: 'var(--ink-muted)' }}>Current Coverage</div>
            <div style={{ fontSize: '1.4rem', fontWeight: 800, color: 'var(--ink)', fontFamily: 'var(--font-serif)' }}>{plan.currentCoverage}%</div>
          </div>

          <div>
            <div style={{ fontSize: '0.72rem', color: 'var(--ink-muted)' }}>Expected Coverage</div>
            <div style={{ fontSize: '1.4rem', fontWeight: 800, color: 'var(--ink)', fontFamily: 'var(--font-serif)' }}>{plan.expectedCoverage}%</div>
          </div>

          <div>
            <div style={{ fontSize: '0.72rem', color: 'var(--atrisk)' }}>Deficit Gap</div>
            <div style={{ fontSize: '1.4rem', fontWeight: 800, color: 'var(--atrisk)', fontFamily: 'var(--font-serif)' }}>{plan.gap}%</div>
          </div>

          <div>
            <div style={{ fontSize: '0.72rem', color: 'var(--ink-muted)' }}>Weeks Remaining</div>
            <div style={{ fontSize: '1.4rem', fontWeight: 800, color: 'var(--ink)', fontFamily: 'var(--font-serif)' }}>{plan.weeksRemaining} Weeks</div>
          </div>

          <div>
            <div style={{ fontSize: '0.72rem', color: 'var(--critical)' }}>Predicted Delay</div>
            <div style={{ fontSize: '1.4rem', fontWeight: 800, color: 'var(--critical)', fontFamily: 'var(--font-serif)' }}>{plan.predictedDelayWeeks} Weeks</div>
          </div>
        </div>
      </div>

      {/* AI Recommendation Highlight Box */}
      <div className="glass-card" style={{
        padding: '24px',
        marginBottom: '24px',
        background: '#FFFFFF',
        border: '1px solid var(--line)',
        borderLeft: '4px solid var(--brass)'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
          <div style={{
            width: '36px',
            height: '36px',
            borderRadius: '6px',
            background: 'var(--ink)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center'
          }}>
            <Sparkles size={18} color="var(--brass)" />
          </div>

          <div>
            <h3 style={{ fontFamily: 'var(--font-serif)', fontSize: '1.2rem', fontWeight: 800, color: 'var(--ink)' }}>
              AI Prescriptive Plan Recommendation
            </h3>
            <span style={{ fontSize: '0.78rem', color: 'var(--ink-muted)', fontWeight: 600 }}>
              Confidence Score: 96% • Conflict Free Target
            </span>
          </div>
        </div>

        <div style={{
          fontSize: '1.2rem',
          fontWeight: 800,
          color: 'var(--ink)',
          marginBottom: '16px',
          background: 'var(--paper)',
          padding: '14px 18px',
          borderRadius: '6px',
          border: '1px solid var(--line)',
          display: 'flex',
          alignItems: 'center',
          gap: '12px',
          fontFamily: 'var(--font-serif)'
        }}>
          <Zap size={22} color="var(--brass)" />
          <span><strong style={{ color: 'var(--atrisk)' }}>{plan.additionalClassesRequired} additional classes</strong> required to get course back on track.</span>
        </div>

        {/* Priority Topics Breakdown */}
        <div style={{ marginBottom: '16px' }}>
          <div style={{ fontSize: '0.82rem', fontWeight: 700, color: 'var(--ink)', marginBottom: '8px' }}>
            Recommended Priority Topics for Recovery Hours:
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '6px' }}>
            {plan.priorityTopics.map((topic, idx) => (
              <div key={idx} style={{
                display: 'flex',
                alignItems: 'center',
                gap: '12px',
                padding: '8px 12px',
                borderRadius: '4px',
                background: 'var(--paper)',
                border: '1px solid var(--line)',
                fontSize: '0.86rem',
                color: 'var(--ink)'
              }}>
                <span style={{
                  width: '22px',
                  height: '22px',
                  borderRadius: '4px',
                  background: '#FFFFFF',
                  border: '1px solid var(--line)',
                  color: 'var(--ink)',
                  fontWeight: 800,
                  fontSize: '0.75rem',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  fontFamily: 'var(--font-serif)'
                }}>
                  {idx + 1}
                </span>
                <span>{topic}</span>
              </div>
            ))}
          </div>
        </div>

        <div style={{ fontSize: '0.82rem', color: 'var(--ink-muted)', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <Clock size={14} color="var(--ink)" /> Recommended Teaching Pace: <strong style={{ color: 'var(--ink)' }}>{plan.recommendedPace}</strong>
        </div>
      </div>

      {/* CTA Button to Timetable Recovery */}
      <div style={{ textAlign: 'right' }}>
        <Link href={`/hod/timetable?courseId=${plan.courseId}`} style={{ textDecoration: 'none' }}>
          <button className="btn-primary" style={{ padding: '12px 24px', fontSize: '0.95rem' }}>
            <Calendar size={18} /> Find Available Timetable Slots <ArrowRight size={18} />
          </button>
        </Link>
      </div>
    </>
  );
}

export default function HodRecoveryPage() {
  return (
    <AppShell>
      <Suspense fallback={<div style={{ padding: '40px', textAlign: 'center', color: '#94a3b8' }}>Loading recovery workspace...</div>}>
        <RecoveryContent />
      </Suspense>
    </AppShell>
  );
}

