'use client';

import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { useSearchParams } from 'next/navigation';
import AppShell from '@/components/ui/AppShell';
import { getRecoveryPlan } from '@/services/recoveryService';
import { RecoveryPlan } from '@/types';
import { Zap, Sparkles, Calendar, Clock, ArrowRight, BookOpen, CheckCircle2, Sliders } from 'lucide-react';

export default function HodRecoveryPage() {
  const searchParams = useSearchParams();
  const courseId = searchParams.get('courseId') || 'course-os-a';

  const [plan, setPlan] = useState<RecoveryPlan | null>(null);
  const [isLoading, setIsLoading] = useState(true);

  useEffect(() => {
    async function loadPlan() {
      const data = await getRecoveryPlan(courseId);
      setPlan(data);
      setIsLoading(false);
    }
    loadPlan();
  }, [courseId]);

  if (isLoading || !plan) {
    return (
      <AppShell>
        <div style={{ padding: '40px', textAlign: 'center', color: '#94a3b8' }}>
          Formulating AI Recovery Plan...
        </div>
      </AppShell>
    );
  }

  return (
    <AppShell>
      {/* Header */}
      <div style={{ marginBottom: '24px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
          <span className="badge" style={{ background: 'linear-gradient(135deg, rgba(236, 72, 153, 0.2), rgba(139, 92, 246, 0.2))', color: '#ec4899', border: '1px solid rgba(236, 72, 153, 0.3)' }}>
            <Sparkles size={12} /> AI Academic Recovery Planner
          </span>
        </div>
        <h1 style={{ fontSize: '1.8rem', fontWeight: 800, color: '#f8fafc', marginBottom: '4px' }}>
          Syllabus Recovery Plan & Recommendations
        </h1>
        <p style={{ color: '#94a3b8', fontSize: '0.9rem' }}>
          Optimized extra-lecture schedule generated by AI to eliminate syllabus deficit before term end.
        </p>
      </div>

      {/* Target Course Summary Glass Card */}
      <div className="glass-card" style={{
        padding: '24px',
        marginBottom: '28px',
        background: 'linear-gradient(135deg, rgba(17, 24, 39, 0.9) 0%, rgba(31, 41, 55, 0.9) 100%)',
        borderColor: 'rgba(99, 102, 241, 0.3)'
      }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
          <div>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '4px' }}>
              <h2 style={{ fontSize: '1.4rem', fontWeight: 800, color: '#f8fafc' }}>
                {plan.courseName}
              </h2>
              <span className="badge" style={{ background: 'rgba(99, 102, 241, 0.2)', color: '#a5b4fc' }}>
                {plan.section}
              </span>
              <span style={{ fontSize: '0.85rem', color: '#94a3b8' }}>
                ({plan.courseCode})
              </span>
            </div>
            <div style={{ fontSize: '0.85rem', color: '#94a3b8' }}>
              Assigned Faculty: <strong style={{ color: '#f8fafc' }}>{plan.facultyName}</strong>
            </div>
          </div>

          <Link href="/hod/recovery/what-if" style={{ textDecoration: 'none' }}>
            <button className="btn-secondary" style={{ padding: '8px 16px', fontSize: '0.82rem', gap: '6px' }}>
              <Sliders size={14} color="#818cf8" /> Open What-If Simulator
            </button>
          </Link>
        </div>

        {/* 4 Metric Badges Row */}
        <div style={{
          display: 'grid',
          gridTemplateColumns: 'repeat(5, 1fr)',
          gap: '14px',
          background: 'rgba(255, 255, 255, 0.03)',
          padding: '16px',
          borderRadius: '12px',
          border: '1px solid rgba(255, 255, 255, 0.06)'
        }}>
          <div>
            <div style={{ fontSize: '0.72rem', color: '#64748b' }}>Current Coverage</div>
            <div style={{ fontSize: '1.4rem', fontWeight: 800, color: '#f8fafc' }}>{plan.currentCoverage}%</div>
          </div>

          <div>
            <div style={{ fontSize: '0.72rem', color: '#64748b' }}>Expected Coverage</div>
            <div style={{ fontSize: '1.4rem', fontWeight: 800, color: '#6366f1' }}>{plan.expectedCoverage}%</div>
          </div>

          <div>
            <div style={{ fontSize: '0.72rem', color: '#ef4444' }}>Deficit Gap</div>
            <div style={{ fontSize: '1.4rem', fontWeight: 800, color: '#ef4444' }}>{plan.gap}%</div>
          </div>

          <div>
            <div style={{ fontSize: '0.72rem', color: '#64748b' }}>Weeks Remaining</div>
            <div style={{ fontSize: '1.4rem', fontWeight: 800, color: '#f8fafc' }}>{plan.weeksRemaining} Weeks</div>
          </div>

          <div>
            <div style={{ fontSize: '0.72rem', color: '#ef4444' }}>Predicted Delay</div>
            <div style={{ fontSize: '1.4rem', fontWeight: 800, color: '#ef4444' }}>{plan.predictedDelayWeeks} Weeks</div>
          </div>
        </div>
      </div>

      {/* AI Recommendation Highlight Box */}
      <div className="glass-card" style={{
        padding: '28px',
        marginBottom: '28px',
        background: 'linear-gradient(135deg, rgba(99, 102, 241, 0.12) 0%, rgba(236, 72, 153, 0.12) 100%)',
        borderColor: 'rgba(236, 72, 153, 0.4)'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
          <div style={{
            width: '36px',
            height: '36px',
            borderRadius: '10px',
            background: 'var(--ai-gradient)',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            boxShadow: '0 0 15px rgba(236, 72, 153, 0.5)'
          }}>
            <Sparkles size={20} color="#ffffff" />
          </div>

          <div>
            <h3 style={{ fontSize: '1.2rem', fontWeight: 800, color: '#f8fafc' }}>
              AI Prescriptive Plan Recommendation
            </h3>
            <span style={{ fontSize: '0.78rem', color: '#ec4899', fontWeight: 600 }}>
              Confidence Score: 96% • Conflict Free Target
            </span>
          </div>
        </div>

        <div style={{
          fontSize: '1.4rem',
          fontWeight: 800,
          color: '#ffffff',
          marginBottom: '16px',
          background: 'rgba(255, 255, 255, 0.05)',
          padding: '16px 20px',
          borderRadius: '14px',
          border: '1px solid rgba(255, 255, 255, 0.1)',
          display: 'flex',
          alignItems: 'center',
          gap: '12px'
        }}>
          <Zap size={24} color="#ec4899" />
          <span><strong style={{ color: '#ec4899' }}>{plan.additionalClassesRequired} additional classes</strong> required to get course back on track.</span>
        </div>

        {/* Priority Topics Breakdown */}
        <div style={{ marginBottom: '20px' }}>
          <div style={{ fontSize: '0.85rem', fontWeight: 700, color: '#cbd5e1', marginBottom: '10px' }}>
            Recommended Priority Topics for Recovery Hours:
          </div>

          <div style={{ display: 'flex', flexDirection: 'column', gap: '8px' }}>
            {plan.priorityTopics.map((topic, idx) => (
              <div key={idx} style={{
                display: 'flex',
                alignItems: 'center',
                gap: '12px',
                padding: '10px 14px',
                borderRadius: '10px',
                background: 'rgba(255, 255, 255, 0.04)',
                border: '1px solid rgba(255, 255, 255, 0.08)',
                fontSize: '0.88rem',
                color: '#f8fafc'
              }}>
                <span style={{
                  width: '24px',
                  height: '24px',
                  borderRadius: '50%',
                  background: 'rgba(99, 102, 241, 0.2)',
                  color: '#818cf8',
                  fontWeight: 800,
                  fontSize: '0.75rem',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center'
                }}>
                  {idx + 1}
                </span>
                <span>{topic}</span>
              </div>
            ))}
          </div>
        </div>

        <div style={{ fontSize: '0.82rem', color: '#94a3b8', display: 'flex', alignItems: 'center', gap: '8px' }}>
          <Clock size={14} color="#818cf8" /> Recommended Teaching Pace: <strong style={{ color: '#f8fafc' }}>{plan.recommendedPace}</strong>
        </div>
      </div>

      {/* CTA Button to Timetable Recovery */}
      <div style={{ textAlign: 'right' }}>
        <Link href={`/hod/timetable?courseId=${plan.courseId}`} style={{ textDecoration: 'none' }}>
          <button className="btn-primary" style={{ padding: '14px 28px', fontSize: '1rem', boxShadow: '0 8px 25px rgba(99, 102, 241, 0.4)' }}>
            <Calendar size={18} /> Find Available Timetable Slots <ArrowRight size={18} />
          </button>
        </Link>
      </div>
    </AppShell>
  );
}
